services:
  web:
    image: python:${{ env.PYTHON_VERSION }}
    command: python main.py
    install:
      - pip install --upgrade pip
      - pip install -r requirements.txt
    environment:
      - PYTHON_VERSION
